APP_NAME = "KawaKeeper"
APP_VERSION = "0.1.0"
APP_STATE = "release"

ENABLE_DISCORD_HANDLER = False
ENABLE_TELEGRAM_HANDLER = False

CONFIG_HARD_DROP = False
DB_HARD_DROP = False
DB_SOFT_DROP = False
DB_TABLES = []