APP_NAME = "Template"
APP_VERSION = "0.0.1"
APP_STATE = "dev"

ENABLE_DISCORD_HANDLER = False
ENABLE_TELEGRAM_HANDLER = True

CONFIG_HARD_DROP = False
DB_HARD_DROP = False
DB_SOFT_DROP = False
DB_TABLES = []